import { createMarketplaceAction } from "@/admin/actions";
import { Empty, Notice } from "@/admin/components";
import { withAdminRepository } from "@/admin/repository";

export default async function MarketplacesPage({ searchParams }: { searchParams: Promise<{ notice?: string }> }) {
  const refs = await withAdminRepository((repo) => repo.references()), query = await searchParams;
  const active = refs.marketplaces.filter((item) => item.active).length;
  return <div className="admin-page"><header className="admin-page-header"><div><p className="admin-kicker">Canais de oferta</p><h2>Marketplaces</h2><p>Gerencie os canais disponíveis para os links e produtos do catálogo.</p></div></header><Notice text={query.notice}/><section className="marketplace-summary" aria-label="Resumo de marketplaces"><div><span>Total</span><strong>{refs.marketplaces.length}</strong></div><div><span>Ativos</span><strong>{active}</strong></div><div><span>Inativos</span><strong>{refs.marketplaces.length - active}</strong></div></section><div className="admin-catalog-layout"><section className="admin-panel admin-records"><header><div><p className="admin-kicker">Canais cadastrados</p><h3>Lista de marketplaces</h3></div><span>{refs.marketplaces.length}</span></header>{refs.marketplaces.length ? <ul className="clean-list">{refs.marketplaces.map((item) => <li key={item.id}><span><strong>{item.name}</strong><small>{item.slug}</small></span><span className={`entity-state ${item.active ? "is-active" : "is-inactive"}`}>{item.active ? "Ativo" : "Inativo"}</span></li>)}</ul> : <Empty title="Nenhum marketplace cadastrado">Crie um canal antes de associá-lo a produtos e links afiliados.</Empty>}</section><section className="admin-panel admin-create-panel"><p className="admin-kicker">Novo canal</p><h3>Criar marketplace</h3><p className="panel-copy">O marketplace poderá ser associado aos produtos conforme as regras existentes.</p><form action={createMarketplaceAction} className="stack-form"><label>Nome<input name="name" required/></label><label>Slug<input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*"/></label><label className="check"><input type="checkbox" name="active" defaultChecked/>Ativo</label><button>Criar marketplace</button></form></section></div></div>;
}
