import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { securityHeaders } from "../next.config";
import { httpsUrl } from "@/admin/validation";
import { safeJsonLd } from "@/seo/structured-data";
describe("SPEC-010 security, privacy and compliance", () => {
  it("sets CSP, clickjacking, referrer and browser capability protections", () => { const headers=Object.fromEntries(securityHeaders.map((h)=>[h.key,h.value])); expect(headers["Content-Security-Policy"]).toContain("object-src 'none'"); expect(headers["Content-Security-Policy"]).toContain("base-uri 'self'"); expect(headers["Content-Security-Policy"]).toContain("frame-ancestors 'none'"); expect(headers["Content-Security-Policy"]).not.toContain("default-src *"); expect(headers["X-Frame-Options"]).toBe("DENY"); expect(headers["Referrer-Policy"]).toBe("strict-origin-when-cross-origin"); expect(headers["X-Content-Type-Options"]).toBe("nosniff"); expect(headers["Permissions-Policy"]).toContain("camera=()"); });
  it("rejects unsafe and oversized administrative URLs", () => { for(const url of ["javascript:alert(1)","data:text/html,x","http://market.example/x","https://localhost/x","https://127.0.0.1/x","https://10.0.0.1/x","https://172.16.0.1/x","https://192.168.0.1/x","https://user:pass@market.example/x","https://market.example/"+"x".repeat(2100)]) expect(()=>httpsUrl(url,"URL")).toThrow(); });
  it("escapes script termination in JSON-LD", () => { expect(safeJsonLd({name:"</script><script>alert(1)</script>"})).not.toContain("</script>"); });
  it("keeps server-only secrets out of client and application sources", () => { const auth=readFileSync("src/lib/admin-auth.ts","utf8"), collector=readFileSync("src/analytics/collector.tsx","utf8"), env=readFileSync(".env.example","utf8"); expect(auth+collector).not.toContain("SUPABASE_SERVICE_ROLE_KEY"); expect(collector).not.toMatch(/DATABASE_URL|ADMIN_USER_IDS|service.role/i); expect(env).toContain("replace-with-server-only-key"); });
  it("keeps every mutation and analytics server-authorized", () => { const actions=readFileSync("src/admin/actions.ts","utf8"), layout=readFileSync("src/app/admin/layout.tsx","utf8"); const mutations=actions.match(/export async function (?!requireAdminMutation)[^(]+/g)??[]; expect(actions.match(/await requireAdminMutation\(\)/g)).toHaveLength(mutations.length); expect(layout).toContain("getAdminBoundaryState"); expect(layout).toContain("redirect"); });
  it("publishes clear legal, affiliate and price disclosures", () => { const legal=["src/legal/content.ts","src/app/privacidade/page.tsx","src/app/termos/page.tsx","src/app/afiliados/page.tsx"].map((f)=>readFileSync(f,"utf8")).join("\n"), layout=readFileSync("src/app/layout.tsx","utf8"), catalog=readFileSync("src/catalog/components.tsx","utf8"); expect(legal).toContain("90 dias"); expect(legal).toContain("não processa a compra"); expect(layout).toContain("links de afiliado"); expect(catalog).toContain("não preço em tempo real"); for(const path of ["/privacidade","/termos","/afiliados"]) expect(layout).toContain(path); });
  it("does not broaden analytics, cookies or production error output", () => { const schema=readFileSync("src/db/schema.ts","utf8"), collector=readFileSync("src/analytics/collector.tsx","utf8"), api=readFileSync("src/app/api/page-view/route.ts","utf8"); expect(schema.slice(schema.indexOf("export const pageViews"))).not.toMatch(/ip|fingerprint|session|cookie|referrer|query.string/i); expect(collector).not.toMatch(/document\.cookie|localStorage|sessionStorage/); expect(api).not.toMatch(/stack|sql|cause|message/); });
  it("preserves /go closed redirect boundaries and production DEMO isolation", () => { const route=readFileSync("src/app/go/[productSlug]/route.ts","utf8"), demo=readFileSync("src/catalog/demo.ts","utf8"), analyticsDemo=readFileSync("src/analytics/demo.ts","utf8"); expect(route).toContain("Cache-Control"); expect(route).toContain("resolveAffiliateRedirect"); expect(route).not.toContain("affiliateLinks"); expect(demo+analyticsDemo).toMatch(/NODE_ENV === "development"/); });
});
