import { ctr, period } from "@/analytics/service";
import { demoAnalytics, demoAnalyticsIsEnabled } from "@/analytics/demo";
import { withAnalyticsRepository } from "@/analytics/drizzle-repository";
import type { AnalyticsSnapshot, RankedItem } from "@/analytics/repository";
import { Empty } from "@/admin/components";

function Ranking({ title, description, rows }: { title: string; description: string; rows: RankedItem[] }) {
  return <section className="admin-panel analytics-ranking-panel"><header><div><h3>{title}</h3><p>{description}</p></div><span>{rows.length}</span></header>{rows.length ? <ol className="analytics-ranking">{rows.map((row) => <li key={row.label}><span>{row.label}</span><strong>{row.value.toLocaleString("pt-BR")}</strong></li>)}</ol> : <Empty title={`Sem dados de ${title.toLowerCase()}`}>Não houve atividade suficiente no período selecionado.</Empty>}</section>;
}

function Trend({ data }: { data: AnalyticsSnapshot["trend"] }) {
  if (!data.length) return <section className="admin-panel analytics-trend-panel"><div className="admin-panel-heading"><div><p className="admin-kicker">Evolução</p><h3>Tendência diária</h3></div></div><Empty title="Sem tendência no período">Visualizações e cliques aparecerão aqui quando houver atividade registrada.</Empty></section>;
  const max = Math.max(1, ...data.flatMap((point) => [point.views, point.clicks]));
  return <section className="admin-panel analytics-trend-panel"><div className="admin-panel-heading"><div><p className="admin-kicker">Evolução</p><h3>Tendência diária</h3></div><div className="chart-legend" aria-hidden="true"><span><i/>Page Views</span><span><i/>Affiliate Clicks</span></div></div><div className="trend" role="img" aria-label="Gráfico diário de Page Views e Affiliate Clicks. Os valores completos estão disponíveis na tabela após o gráfico.">{data.map((point) => <div className="trend-day" key={point.date}><span className="trend-bars"><i style={{ height: `${point.views / max * 100}%` }}/><b style={{ height: `${point.clicks / max * 100}%` }}/></span><small>{new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "2-digit", timeZone: "UTC" }).format(new Date(`${point.date}T00:00:00Z`))}</small></div>)}</div><details className="trend-data"><summary>Consultar valores do gráfico</summary><div className="table-wrap" role="region" aria-label="Valores diários de Analytics" tabIndex={0}><table><thead><tr><th scope="col">Data</th><th scope="col">Page Views</th><th scope="col">Affiliate Clicks</th></tr></thead><tbody>{data.map((point) => <tr key={point.date}><th scope="row">{new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeZone: "UTC" }).format(new Date(`${point.date}T00:00:00Z`))}</th><td>{point.views.toLocaleString("pt-BR")}</td><td>{point.clicks.toLocaleString("pt-BR")}</td></tr>)}</tbody></table></div></details></section>;
}

export default async function AnalyticsPage({ searchParams }: { searchParams: Promise<{ days?: string }> }) {
  const days = period((await searchParams).days), demo = demoAnalyticsIsEnabled(), data = demo ? demoAnalytics(days) : await withAnalyticsRepository((repo) => repo.snapshot(days)), rate = ctr(data.affiliateClicks, data.pageViews);
  return <div className="admin-page analytics-page"><header className="admin-page-header"><div><p className="admin-kicker">Performance agregada {demo && <span className="pill">DEMO</span>}</p><h2>Analytics</h2><p>Leitura consolidada da audiência e dos cliques afiliados registrados.</p></div><nav className="periods" aria-label="Período">{[7, 30, 90].map((value) => <a className={days === value ? "selected" : ""} aria-current={days === value ? "page" : undefined} href={`?days=${value}`} key={value}>{value} dias</a>)}</nav></header><section className="analytics-summary" aria-label={`Resumo dos últimos ${days} dias`}><article className="admin-kpi admin-kpi-featured"><span className="admin-kpi-label">Page Views</span><strong>{data.pageViews.toLocaleString("pt-BR")}</strong><small>Visualizações registradas</small></article><article className="admin-kpi"><span className="admin-kpi-label">Affiliate Clicks</span><strong>{data.affiliateClicks.toLocaleString("pt-BR")}</strong><small>Cliques afiliados registrados</small></article><article className="admin-kpi"><span className="admin-kpi-label">CTR</span><strong>{rate.toLocaleString("pt-BR", { maximumFractionDigits: 1 })}%</strong><small>Cliques sobre visualizações</small></article><div className="analytics-compact-kpis"><article><span>Produtos ativos</span><strong>{data.activeProducts.toLocaleString("pt-BR")}</strong></article><article><span>Produtos com clique</span><strong>{data.productsWithClicks.toLocaleString("pt-BR")}</strong></article></div></section><section className="analytics-business-context" aria-label="Contexto gerencial"><div><p className="admin-kicker">Receita confirmada</p><strong>Dados ainda não disponíveis</strong><p>Nenhum valor financeiro é inferido a partir de cliques.</p></div><div><p className="admin-kicker">Target mensal</p><strong>R$ 7.000/mês</strong><p>Meta gerencial; não é receita nem progresso financeiro.</p></div></section><Trend data={data.trend}/><div className="analytics-grid"><Ranking title="Produtos por clique" description="Produtos com mais cliques afiliados" rows={data.products}/><Ranking title="Categorias" description="Atividade agregada por categoria" rows={data.categories}/><Ranking title="Origens de tráfego" description="Canais registrados nas visualizações" rows={data.trafficSources}/><Ranking title="Páginas de origem dos cliques" description="Origem interna dos cliques afiliados" rows={data.sourcePages}/><Ranking title="Tipos de página" description="Visualizações por contexto de página" rows={data.pageTypes}/></div></div>;
}
